name: Publish .NET 8 Desktop App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Publish Windows
      run: dotnet publish ./Frosty/Frosty.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/windows
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-app
        path: ./publish/windows

  publish-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Publish Linux
      run: dotnet publish ./Frosty/Frosty.csproj -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/linux
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-app
        path: ./publish/linux
