name: Publish .NET 8 Desktop App
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        arch: [x64, x86]
        include:
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Cache .NET dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Publish
      run: dotnet publish ./Frosty/Frosty.csproj --configuration Release --runtime ${{ matrix.platform }}-${{ matrix.arch }} --self-contained true --output ./publish
    - name: Zip artifact
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          Compress-Archive -Path ./publish/* -DestinationPath ./Frosty-${{ matrix.platform }}-${{ matrix.arch }}.zip
        else
          zip -r ./Frosty-${{ matrix.platform }}-${{ matrix.arch }}.zip ./publish
        fi
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}
        path: ./Frosty-${{ matrix.platform }}-${{ matrix.arch }}.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Validate artifacts
      run: |
        for file in ./*/*.zip; do
          if ! unzip -t "$file" > /dev/null; then
            echo "Error: $file is not a valid zip file"
            exit 1
          fi
        done
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        assets=""
        for file in ./*/*.zip; do
          assets="$assets $file"
        done
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --generate-notes \
          $assets